syntax = "proto3";

package common;

import "google/protobuf/timestamp.proto";

option go_package = "/common";

message ListParamsSt {
  int64 page = 1;
  int64 page_size = 2;
  bool with_total_count = 3;
  bool only_count = 4;
  string sort_name = 5;
  repeated string sort = 6;
}

message PaginationInfoSt {
  int64 page = 1;
  int64 page_size = 2;
  int64 total_count = 3;
}

message TimeRange {
  google.protobuf.Timestamp start_at = 1;
  google.protobuf.Timestamp end_at = 2;
}

message GeoPoint {
  double lat = 1;
  double lng = 2;
}

message ErrorDetail {
  string code = 1;
  string message = 2;
  map<string, string> fields = 3;
}

message FileData {
  string name = 1;
  string extension = 2;
  string mime_type = 3;
  bytes data = 4;
}
