// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: booking_v1/audit.proto

package booking_v1

import (
	common "github.com/zhamspace/booking/pkg/proto/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditMain struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	User       *AccountMain           `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Resource   string                 `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`
	ObjectId   string                 `protobuf:"bytes,6,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	ChangeType string                 `protobuf:"bytes,7,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	// Types that are valid to be assigned to Object:
	//
	//	*AuditMain_Raw
	//	*AuditMain_Booking
	Object        isAuditMain_Object `protobuf_oneof:"object"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditMain) Reset() {
	*x = AuditMain{}
	mi := &file_booking_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditMain) ProtoMessage() {}

func (x *AuditMain) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditMain.ProtoReflect.Descriptor instead.
func (*AuditMain) Descriptor() ([]byte, []int) {
	return file_booking_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditMain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditMain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AuditMain) GetUser() *AccountMain {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuditMain) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuditMain) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *AuditMain) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *AuditMain) GetObject() isAuditMain_Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *AuditMain) GetRaw() *structpb.Struct {
	if x != nil {
		if x, ok := x.Object.(*AuditMain_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *AuditMain) GetBooking() *BookingMain {
	if x != nil {
		if x, ok := x.Object.(*AuditMain_Booking); ok {
			return x.Booking
		}
	}
	return nil
}

type isAuditMain_Object interface {
	isAuditMain_Object()
}

type AuditMain_Raw struct {
	Raw *structpb.Struct `protobuf:"bytes,8,opt,name=raw,proto3,oneof"`
}

type AuditMain_Booking struct {
	Booking *BookingMain `protobuf:"bytes,9,opt,name=booking,proto3,oneof"`
}

func (*AuditMain_Raw) isAuditMain_Object() {}

func (*AuditMain_Booking) isAuditMain_Object() {}

type AccountMain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountMain) Reset() {
	*x = AccountMain{}
	mi := &file_booking_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountMain) ProtoMessage() {}

func (x *AccountMain) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountMain.ProtoReflect.Descriptor instead.
func (*AccountMain) Descriptor() ([]byte, []int) {
	return file_booking_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *AccountMain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountMain) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AccountMain) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AccountMain) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AccountMain) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountMain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AuditListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListParams    *common.ListParamsSt   `protobuf:"bytes,1,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	Resource      *string                `protobuf:"bytes,3,opt,name=resource,proto3,oneof" json:"resource,omitempty"`
	ObjectId      *string                `protobuf:"bytes,4,opt,name=object_id,json=objectId,proto3,oneof" json:"object_id,omitempty"`
	ChangeType    *string                `protobuf:"bytes,5,opt,name=change_type,json=changeType,proto3,oneof" json:"change_type,omitempty"`
	UserId        *string                `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditListReq) Reset() {
	*x = AuditListReq{}
	mi := &file_booking_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditListReq) ProtoMessage() {}

func (x *AuditListReq) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditListReq.ProtoReflect.Descriptor instead.
func (*AuditListReq) Descriptor() ([]byte, []int) {
	return file_booking_v1_audit_proto_rawDescGZIP(), []int{2}
}

func (x *AuditListReq) GetListParams() *common.ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

func (x *AuditListReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *AuditListReq) GetResource() string {
	if x != nil && x.Resource != nil {
		return *x.Resource
	}
	return ""
}

func (x *AuditListReq) GetObjectId() string {
	if x != nil && x.ObjectId != nil {
		return *x.ObjectId
	}
	return ""
}

func (x *AuditListReq) GetChangeType() string {
	if x != nil && x.ChangeType != nil {
		return *x.ChangeType
	}
	return ""
}

func (x *AuditListReq) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type AuditListRep struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	PaginationInfo *common.PaginationInfoSt `protobuf:"bytes,1,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	Results        []*AuditMain             `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuditListRep) Reset() {
	*x = AuditListRep{}
	mi := &file_booking_v1_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditListRep) ProtoMessage() {}

func (x *AuditListRep) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditListRep.ProtoReflect.Descriptor instead.
func (*AuditListRep) Descriptor() ([]byte, []int) {
	return file_booking_v1_audit_proto_rawDescGZIP(), []int{3}
}

func (x *AuditListRep) GetPaginationInfo() *common.PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

func (x *AuditListRep) GetResults() []*AuditMain {
	if x != nil {
		return x.Results
	}
	return nil
}

type AuditGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditGetReq) Reset() {
	*x = AuditGetReq{}
	mi := &file_booking_v1_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditGetReq) ProtoMessage() {}

func (x *AuditGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditGetReq.ProtoReflect.Descriptor instead.
func (*AuditGetReq) Descriptor() ([]byte, []int) {
	return file_booking_v1_audit_proto_rawDescGZIP(), []int{4}
}

func (x *AuditGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_booking_v1_audit_proto protoreflect.FileDescriptor

const file_booking_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x16booking_v1/audit.proto\x12\x10booking_v1.audit\x1a\x13common/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18booking_v1/booking.proto\"\xd7\x02\n" +
	"\tAuditMain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x121\n" +
	"\x04user\x18\x04 \x01(\v2\x1d.booking_v1.audit.AccountMainR\x04user\x12\x1a\n" +
	"\bresource\x18\x05 \x01(\tR\bresource\x12\x1b\n" +
	"\tobject_id\x18\x06 \x01(\tR\bobjectId\x12\x1f\n" +
	"\vchange_type\x18\a \x01(\tR\n" +
	"changeType\x12+\n" +
	"\x03raw\x18\b \x01(\v2\x17.google.protobuf.StructH\x00R\x03raw\x12;\n" +
	"\abooking\x18\t \x01(\v2\x1f.booking_v1.booking.BookingMainH\x00R\abookingB\b\n" +
	"\x06object\"\xc6\x01\n" +
	"\vAccountMain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x95\x02\n" +
	"\fAuditListReq\x125\n" +
	"\vlist_params\x18\x01 \x01(\v2\x14.common.ListParamsStR\n" +
	"listParams\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\x12\x1f\n" +
	"\bresource\x18\x03 \x01(\tH\x00R\bresource\x88\x01\x01\x12 \n" +
	"\tobject_id\x18\x04 \x01(\tH\x01R\bobjectId\x88\x01\x01\x12$\n" +
	"\vchange_type\x18\x05 \x01(\tH\x02R\n" +
	"changeType\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x06 \x01(\tH\x03R\x06userId\x88\x01\x01B\v\n" +
	"\t_resourceB\f\n" +
	"\n" +
	"_object_idB\x0e\n" +
	"\f_change_typeB\n" +
	"\n" +
	"\b_user_id\"\x88\x01\n" +
	"\fAuditListRep\x12A\n" +
	"\x0fpagination_info\x18\x01 \x01(\v2\x18.common.PaginationInfoStR\x0epaginationInfo\x125\n" +
	"\aresults\x18\x02 \x03(\v2\x1b.booking_v1.audit.AuditMainR\aresults\"\x1d\n" +
	"\vAuditGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xb7\x01\n" +
	"\x05Audit\x12V\n" +
	"\x04List\x12\x1e.booking_v1.audit.AuditListReq\x1a\x1e.booking_v1.audit.AuditListRep\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/audit\x12V\n" +
	"\x03Get\x12\x1d.booking_v1.audit.AuditGetReq\x1a\x1b.booking_v1.audit.AuditMain\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/audit/{id}B\rZ\v/booking_v1b\x06proto3"

var (
	file_booking_v1_audit_proto_rawDescOnce sync.Once
	file_booking_v1_audit_proto_rawDescData []byte
)

func file_booking_v1_audit_proto_rawDescGZIP() []byte {
	file_booking_v1_audit_proto_rawDescOnce.Do(func() {
		file_booking_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_audit_proto_rawDesc), len(file_booking_v1_audit_proto_rawDesc)))
	})
	return file_booking_v1_audit_proto_rawDescData
}

var file_booking_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_booking_v1_audit_proto_goTypes = []any{
	(*AuditMain)(nil),               // 0: booking_v1.audit.AuditMain
	(*AccountMain)(nil),             // 1: booking_v1.audit.AccountMain
	(*AuditListReq)(nil),            // 2: booking_v1.audit.AuditListReq
	(*AuditListRep)(nil),            // 3: booking_v1.audit.AuditListRep
	(*AuditGetReq)(nil),             // 4: booking_v1.audit.AuditGetReq
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
	(*structpb.Struct)(nil),         // 6: google.protobuf.Struct
	(*BookingMain)(nil),             // 7: booking_v1.booking.BookingMain
	(*common.ListParamsSt)(nil),     // 8: common.ListParamsSt
	(*common.PaginationInfoSt)(nil), // 9: common.PaginationInfoSt
}
var file_booking_v1_audit_proto_depIdxs = []int32{
	5,  // 0: booking_v1.audit.AuditMain.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: booking_v1.audit.AuditMain.user:type_name -> booking_v1.audit.AccountMain
	6,  // 2: booking_v1.audit.AuditMain.raw:type_name -> google.protobuf.Struct
	7,  // 3: booking_v1.audit.AuditMain.booking:type_name -> booking_v1.booking.BookingMain
	5,  // 4: booking_v1.audit.AccountMain.created_at:type_name -> google.protobuf.Timestamp
	8,  // 5: booking_v1.audit.AuditListReq.list_params:type_name -> common.ListParamsSt
	9,  // 6: booking_v1.audit.AuditListRep.pagination_info:type_name -> common.PaginationInfoSt
	0,  // 7: booking_v1.audit.AuditListRep.results:type_name -> booking_v1.audit.AuditMain
	2,  // 8: booking_v1.audit.Audit.List:input_type -> booking_v1.audit.AuditListReq
	4,  // 9: booking_v1.audit.Audit.Get:input_type -> booking_v1.audit.AuditGetReq
	3,  // 10: booking_v1.audit.Audit.List:output_type -> booking_v1.audit.AuditListRep
	0,  // 11: booking_v1.audit.Audit.Get:output_type -> booking_v1.audit.AuditMain
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_booking_v1_audit_proto_init() }
func file_booking_v1_audit_proto_init() {
	if File_booking_v1_audit_proto != nil {
		return
	}
	file_booking_v1_booking_proto_init()
	file_booking_v1_audit_proto_msgTypes[0].OneofWrappers = []any{
		(*AuditMain_Raw)(nil),
		(*AuditMain_Booking)(nil),
	}
	file_booking_v1_audit_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_audit_proto_rawDesc), len(file_booking_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_v1_audit_proto_goTypes,
		DependencyIndexes: file_booking_v1_audit_proto_depIdxs,
		MessageInfos:      file_booking_v1_audit_proto_msgTypes,
	}.Build()
	File_booking_v1_audit_proto = out.File
	file_booking_v1_audit_proto_goTypes = nil
	file_booking_v1_audit_proto_depIdxs = nil
}
