// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: booking_v1/booking.proto

package booking_v1

import (
	common "github.com/zhamspace/booking/pkg/proto/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookingMain struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VenueId         string                 `protobuf:"bytes,2,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	ResourceId      string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	SessionId       *string                `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	UserId          string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	PaymentStatus   string                 `protobuf:"bytes,7,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	PriceTotal      int64                  `protobuf:"varint,8,opt,name=price_total,json=priceTotal,proto3" json:"price_total,omitempty"`
	Currency        string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	StartAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt           *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Timezone        string                 `protobuf:"bytes,12,opt,name=timezone,proto3" json:"timezone,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	HoldExpiresAt   *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=hold_expires_at,json=holdExpiresAt,proto3,oneof" json:"hold_expires_at,omitempty"`
	PaymentIntentId *string                `protobuf:"bytes,16,opt,name=payment_intent_id,json=paymentIntentId,proto3,oneof" json:"payment_intent_id,omitempty"`
	CancelReason    *string                `protobuf:"bytes,17,opt,name=cancel_reason,json=cancelReason,proto3,oneof" json:"cancel_reason,omitempty"`
	CancelledAt     *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=cancelled_at,json=cancelledAt,proto3,oneof" json:"cancelled_at,omitempty"`
	ConfirmedAt     *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=confirmed_at,json=confirmedAt,proto3,oneof" json:"confirmed_at,omitempty"`
	CompletedAt     *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BookingMain) Reset() {
	*x = BookingMain{}
	mi := &file_booking_v1_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingMain) ProtoMessage() {}

func (x *BookingMain) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingMain.ProtoReflect.Descriptor instead.
func (*BookingMain) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{0}
}

func (x *BookingMain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookingMain) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *BookingMain) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *BookingMain) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *BookingMain) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BookingMain) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BookingMain) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *BookingMain) GetPriceTotal() int64 {
	if x != nil {
		return x.PriceTotal
	}
	return 0
}

func (x *BookingMain) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BookingMain) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *BookingMain) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *BookingMain) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *BookingMain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BookingMain) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BookingMain) GetHoldExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.HoldExpiresAt
	}
	return nil
}

func (x *BookingMain) GetPaymentIntentId() string {
	if x != nil && x.PaymentIntentId != nil {
		return *x.PaymentIntentId
	}
	return ""
}

func (x *BookingMain) GetCancelReason() string {
	if x != nil && x.CancelReason != nil {
		return *x.CancelReason
	}
	return ""
}

func (x *BookingMain) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

func (x *BookingMain) GetConfirmedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConfirmedAt
	}
	return nil
}

func (x *BookingMain) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type BookingListReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ListParams       *common.ListParamsSt   `protobuf:"bytes,1,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	Ids              []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	VenueId          *string                `protobuf:"bytes,3,opt,name=venue_id,json=venueId,proto3,oneof" json:"venue_id,omitempty"`
	ResourceId       *string                `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3,oneof" json:"resource_id,omitempty"`
	UserId           *string                `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	SessionId        *string                `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	Status           *string                `protobuf:"bytes,7,opt,name=status,proto3,oneof" json:"status,omitempty"`
	PaymentStatus    *string                `protobuf:"bytes,8,opt,name=payment_status,json=paymentStatus,proto3,oneof" json:"payment_status,omitempty"`
	From             *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=from,proto3,oneof" json:"from,omitempty"`
	To               *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=to,proto3,oneof" json:"to,omitempty"`
	IncludeCancelled bool                   `protobuf:"varint,11,opt,name=include_cancelled,json=includeCancelled,proto3" json:"include_cancelled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BookingListReq) Reset() {
	*x = BookingListReq{}
	mi := &file_booking_v1_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingListReq) ProtoMessage() {}

func (x *BookingListReq) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingListReq.ProtoReflect.Descriptor instead.
func (*BookingListReq) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{1}
}

func (x *BookingListReq) GetListParams() *common.ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

func (x *BookingListReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *BookingListReq) GetVenueId() string {
	if x != nil && x.VenueId != nil {
		return *x.VenueId
	}
	return ""
}

func (x *BookingListReq) GetResourceId() string {
	if x != nil && x.ResourceId != nil {
		return *x.ResourceId
	}
	return ""
}

func (x *BookingListReq) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *BookingListReq) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *BookingListReq) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *BookingListReq) GetPaymentStatus() string {
	if x != nil && x.PaymentStatus != nil {
		return *x.PaymentStatus
	}
	return ""
}

func (x *BookingListReq) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *BookingListReq) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *BookingListReq) GetIncludeCancelled() bool {
	if x != nil {
		return x.IncludeCancelled
	}
	return false
}

type BookingListRep struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	PaginationInfo *common.PaginationInfoSt `protobuf:"bytes,1,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	Results        []*BookingMain           `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BookingListRep) Reset() {
	*x = BookingListRep{}
	mi := &file_booking_v1_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingListRep) ProtoMessage() {}

func (x *BookingListRep) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingListRep.ProtoReflect.Descriptor instead.
func (*BookingListRep) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{2}
}

func (x *BookingListRep) GetPaginationInfo() *common.PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

func (x *BookingListRep) GetResults() []*BookingMain {
	if x != nil {
		return x.Results
	}
	return nil
}

type BookingGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingGetReq) Reset() {
	*x = BookingGetReq{}
	mi := &file_booking_v1_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingGetReq) ProtoMessage() {}

func (x *BookingGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingGetReq.ProtoReflect.Descriptor instead.
func (*BookingGetReq) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{3}
}

func (x *BookingGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BookingCreateReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VenueId        string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	ResourceId     string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	StartAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Timezone       string                 `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`
	SessionId      *string                `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	UserId         *string                `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	PriceTotal     *int64                 `protobuf:"varint,8,opt,name=price_total,json=priceTotal,proto3,oneof" json:"price_total,omitempty"`
	Currency       *string                `protobuf:"bytes,9,opt,name=currency,proto3,oneof" json:"currency,omitempty"`
	PriceQuoteId   *string                `protobuf:"bytes,10,opt,name=price_quote_id,json=priceQuoteId,proto3,oneof" json:"price_quote_id,omitempty"`
	IdempotencyKey *string                `protobuf:"bytes,11,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`
	Note           *string                `protobuf:"bytes,12,opt,name=note,proto3,oneof" json:"note,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BookingCreateReq) Reset() {
	*x = BookingCreateReq{}
	mi := &file_booking_v1_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingCreateReq) ProtoMessage() {}

func (x *BookingCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingCreateReq.ProtoReflect.Descriptor instead.
func (*BookingCreateReq) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{4}
}

func (x *BookingCreateReq) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *BookingCreateReq) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *BookingCreateReq) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *BookingCreateReq) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *BookingCreateReq) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *BookingCreateReq) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *BookingCreateReq) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *BookingCreateReq) GetPriceTotal() int64 {
	if x != nil && x.PriceTotal != nil {
		return *x.PriceTotal
	}
	return 0
}

func (x *BookingCreateReq) GetCurrency() string {
	if x != nil && x.Currency != nil {
		return *x.Currency
	}
	return ""
}

func (x *BookingCreateReq) GetPriceQuoteId() string {
	if x != nil && x.PriceQuoteId != nil {
		return *x.PriceQuoteId
	}
	return ""
}

func (x *BookingCreateReq) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

func (x *BookingCreateReq) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

type BookingConfirmReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentIntentId *string                `protobuf:"bytes,2,opt,name=payment_intent_id,json=paymentIntentId,proto3,oneof" json:"payment_intent_id,omitempty"`
	IdempotencyKey  *string                `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BookingConfirmReq) Reset() {
	*x = BookingConfirmReq{}
	mi := &file_booking_v1_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingConfirmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingConfirmReq) ProtoMessage() {}

func (x *BookingConfirmReq) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingConfirmReq.ProtoReflect.Descriptor instead.
func (*BookingConfirmReq) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{5}
}

func (x *BookingConfirmReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookingConfirmReq) GetPaymentIntentId() string {
	if x != nil && x.PaymentIntentId != nil {
		return *x.PaymentIntentId
	}
	return ""
}

func (x *BookingConfirmReq) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

type BookingCancelReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason          *string                `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	RefundRequested *bool                  `protobuf:"varint,3,opt,name=refund_requested,json=refundRequested,proto3,oneof" json:"refund_requested,omitempty"`
	IdempotencyKey  *string                `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BookingCancelReq) Reset() {
	*x = BookingCancelReq{}
	mi := &file_booking_v1_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingCancelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingCancelReq) ProtoMessage() {}

func (x *BookingCancelReq) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingCancelReq.ProtoReflect.Descriptor instead.
func (*BookingCancelReq) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{6}
}

func (x *BookingCancelReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookingCancelReq) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *BookingCancelReq) GetRefundRequested() bool {
	if x != nil && x.RefundRequested != nil {
		return *x.RefundRequested
	}
	return false
}

func (x *BookingCancelReq) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

type BookingStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueIds      []string               `protobuf:"bytes,1,rep,name=venue_ids,json=venueIds,proto3" json:"venue_ids,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3,oneof" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3,oneof" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingStatsReq) Reset() {
	*x = BookingStatsReq{}
	mi := &file_booking_v1_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingStatsReq) ProtoMessage() {}

func (x *BookingStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingStatsReq.ProtoReflect.Descriptor instead.
func (*BookingStatsReq) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{7}
}

func (x *BookingStatsReq) GetVenueIds() []string {
	if x != nil {
		return x.VenueIds
	}
	return nil
}

func (x *BookingStatsReq) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *BookingStatsReq) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type BookingStatsRep struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalBookings     int64                  `protobuf:"varint,1,opt,name=total_bookings,json=totalBookings,proto3" json:"total_bookings,omitempty"`
	ConfirmedBookings int64                  `protobuf:"varint,2,opt,name=confirmed_bookings,json=confirmedBookings,proto3" json:"confirmed_bookings,omitempty"`
	CancelledBookings int64                  `protobuf:"varint,3,opt,name=cancelled_bookings,json=cancelledBookings,proto3" json:"cancelled_bookings,omitempty"`
	TotalRevenue      int64                  `protobuf:"varint,4,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	Currency          string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	RevenueByDay      []*DayStat             `protobuf:"bytes,6,rep,name=revenue_by_day,json=revenueByDay,proto3" json:"revenue_by_day,omitempty"`
	BookingsByDay     []*DayStat             `protobuf:"bytes,7,rep,name=bookings_by_day,json=bookingsByDay,proto3" json:"bookings_by_day,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BookingStatsRep) Reset() {
	*x = BookingStatsRep{}
	mi := &file_booking_v1_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingStatsRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingStatsRep) ProtoMessage() {}

func (x *BookingStatsRep) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingStatsRep.ProtoReflect.Descriptor instead.
func (*BookingStatsRep) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{8}
}

func (x *BookingStatsRep) GetTotalBookings() int64 {
	if x != nil {
		return x.TotalBookings
	}
	return 0
}

func (x *BookingStatsRep) GetConfirmedBookings() int64 {
	if x != nil {
		return x.ConfirmedBookings
	}
	return 0
}

func (x *BookingStatsRep) GetCancelledBookings() int64 {
	if x != nil {
		return x.CancelledBookings
	}
	return 0
}

func (x *BookingStatsRep) GetTotalRevenue() int64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *BookingStatsRep) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BookingStatsRep) GetRevenueByDay() []*DayStat {
	if x != nil {
		return x.RevenueByDay
	}
	return nil
}

func (x *BookingStatsRep) GetBookingsByDay() []*DayStat {
	if x != nil {
		return x.BookingsByDay
	}
	return nil
}

type DayStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayStat) Reset() {
	*x = DayStat{}
	mi := &file_booking_v1_booking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayStat) ProtoMessage() {}

func (x *DayStat) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayStat.ProtoReflect.Descriptor instead.
func (*DayStat) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{9}
}

func (x *DayStat) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DayStat) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_booking_v1_booking_proto protoreflect.FileDescriptor

const file_booking_v1_booking_proto_rawDesc = "" +
	"\n" +
	"\x18booking_v1/booking.proto\x12\x12booking_v1.booking\x1a\x13common/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\a\n" +
	"\vBookingMain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bvenue_id\x18\x02 \x01(\tR\avenueId\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12\"\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tH\x00R\tsessionId\x88\x01\x01\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12%\n" +
	"\x0epayment_status\x18\a \x01(\tR\rpaymentStatus\x12\x1f\n" +
	"\vprice_total\x18\b \x01(\x03R\n" +
	"priceTotal\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x125\n" +
	"\bstart_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\x12\x1a\n" +
	"\btimezone\x18\f \x01(\tR\btimezone\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12G\n" +
	"\x0fhold_expires_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampH\x01R\rholdExpiresAt\x88\x01\x01\x12/\n" +
	"\x11payment_intent_id\x18\x10 \x01(\tH\x02R\x0fpaymentIntentId\x88\x01\x01\x12(\n" +
	"\rcancel_reason\x18\x11 \x01(\tH\x03R\fcancelReason\x88\x01\x01\x12B\n" +
	"\fcancelled_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\vcancelledAt\x88\x01\x01\x12B\n" +
	"\fconfirmed_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampH\x05R\vconfirmedAt\x88\x01\x01\x12B\n" +
	"\fcompleted_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampH\x06R\vcompletedAt\x88\x01\x01B\r\n" +
	"\v_session_idB\x12\n" +
	"\x10_hold_expires_atB\x14\n" +
	"\x12_payment_intent_idB\x10\n" +
	"\x0e_cancel_reasonB\x0f\n" +
	"\r_cancelled_atB\x0f\n" +
	"\r_confirmed_atB\x0f\n" +
	"\r_completed_at\"\xa3\x04\n" +
	"\x0eBookingListReq\x125\n" +
	"\vlist_params\x18\x01 \x01(\v2\x14.common.ListParamsStR\n" +
	"listParams\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\x12\x1e\n" +
	"\bvenue_id\x18\x03 \x01(\tH\x00R\avenueId\x88\x01\x01\x12$\n" +
	"\vresource_id\x18\x04 \x01(\tH\x01R\n" +
	"resourceId\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x05 \x01(\tH\x02R\x06userId\x88\x01\x01\x12\"\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tH\x03R\tsessionId\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\a \x01(\tH\x04R\x06status\x88\x01\x01\x12*\n" +
	"\x0epayment_status\x18\b \x01(\tH\x05R\rpaymentStatus\x88\x01\x01\x123\n" +
	"\x04from\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x06R\x04from\x88\x01\x01\x12/\n" +
	"\x02to\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\aR\x02to\x88\x01\x01\x12+\n" +
	"\x11include_cancelled\x18\v \x01(\bR\x10includeCancelledB\v\n" +
	"\t_venue_idB\x0e\n" +
	"\f_resource_idB\n" +
	"\n" +
	"\b_user_idB\r\n" +
	"\v_session_idB\t\n" +
	"\a_statusB\x11\n" +
	"\x0f_payment_statusB\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_to\"\x8e\x01\n" +
	"\x0eBookingListRep\x12A\n" +
	"\x0fpagination_info\x18\x01 \x01(\v2\x18.common.PaginationInfoStR\x0epaginationInfo\x129\n" +
	"\aresults\x18\x02 \x03(\v2\x1f.booking_v1.booking.BookingMainR\aresults\"\x1f\n" +
	"\rBookingGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb7\x04\n" +
	"\x10BookingCreateReq\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x125\n" +
	"\bstart_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\x12\x1a\n" +
	"\btimezone\x18\x05 \x01(\tR\btimezone\x12\"\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tH\x00R\tsessionId\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\a \x01(\tH\x01R\x06userId\x88\x01\x01\x12$\n" +
	"\vprice_total\x18\b \x01(\x03H\x02R\n" +
	"priceTotal\x88\x01\x01\x12\x1f\n" +
	"\bcurrency\x18\t \x01(\tH\x03R\bcurrency\x88\x01\x01\x12)\n" +
	"\x0eprice_quote_id\x18\n" +
	" \x01(\tH\x04R\fpriceQuoteId\x88\x01\x01\x12,\n" +
	"\x0fidempotency_key\x18\v \x01(\tH\x05R\x0eidempotencyKey\x88\x01\x01\x12\x17\n" +
	"\x04note\x18\f \x01(\tH\x06R\x04note\x88\x01\x01B\r\n" +
	"\v_session_idB\n" +
	"\n" +
	"\b_user_idB\x0e\n" +
	"\f_price_totalB\v\n" +
	"\t_currencyB\x11\n" +
	"\x0f_price_quote_idB\x12\n" +
	"\x10_idempotency_keyB\a\n" +
	"\x05_note\"\xac\x01\n" +
	"\x11BookingConfirmReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x11payment_intent_id\x18\x02 \x01(\tH\x00R\x0fpaymentIntentId\x88\x01\x01\x12,\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tH\x01R\x0eidempotencyKey\x88\x01\x01B\x14\n" +
	"\x12_payment_intent_idB\x12\n" +
	"\x10_idempotency_key\"\xd1\x01\n" +
	"\x10BookingCancelReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\x06reason\x18\x02 \x01(\tH\x00R\x06reason\x88\x01\x01\x12.\n" +
	"\x10refund_requested\x18\x03 \x01(\bH\x01R\x0frefundRequested\x88\x01\x01\x12,\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tH\x02R\x0eidempotencyKey\x88\x01\x01B\t\n" +
	"\a_reasonB\x13\n" +
	"\x11_refund_requestedB\x12\n" +
	"\x10_idempotency_key\"\xa4\x01\n" +
	"\x0fBookingStatsReq\x12\x1b\n" +
	"\tvenue_ids\x18\x01 \x03(\tR\bvenueIds\x123\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04from\x88\x01\x01\x12/\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x02to\x88\x01\x01B\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_to\"\xdf\x02\n" +
	"\x0fBookingStatsRep\x12%\n" +
	"\x0etotal_bookings\x18\x01 \x01(\x03R\rtotalBookings\x12-\n" +
	"\x12confirmed_bookings\x18\x02 \x01(\x03R\x11confirmedBookings\x12-\n" +
	"\x12cancelled_bookings\x18\x03 \x01(\x03R\x11cancelledBookings\x12#\n" +
	"\rtotal_revenue\x18\x04 \x01(\x03R\ftotalRevenue\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12A\n" +
	"\x0erevenue_by_day\x18\x06 \x03(\v2\x1b.booking_v1.booking.DayStatR\frevenueByDay\x12C\n" +
	"\x0fbookings_by_day\x18\a \x03(\v2\x1b.booking_v1.booking.DayStatR\rbookingsByDay\"3\n" +
	"\aDayStat\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value2\x8b\x05\n" +
	"\aBooking\x12a\n" +
	"\x04List\x12\".booking_v1.booking.BookingListReq\x1a\".booking_v1.booking.BookingListRep\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/bookings\x12a\n" +
	"\x03Get\x12!.booking_v1.booking.BookingGetReq\x1a\x1f.booking_v1.booking.BookingMain\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/bookings/{id}\x12e\n" +
	"\x06Create\x12$.booking_v1.booking.BookingCreateReq\x1a\x1f.booking_v1.booking.BookingMain\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/bookings\x12t\n" +
	"\aConfirm\x12%.booking_v1.booking.BookingConfirmReq\x1a\x1f.booking_v1.booking.BookingMain\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/bookings/{id}/confirm\x12q\n" +
	"\x06Cancel\x12$.booking_v1.booking.BookingCancelReq\x1a\x1f.booking_v1.booking.BookingMain\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/bookings/{id}/cancel\x12j\n" +
	"\x05Stats\x12#.booking_v1.booking.BookingStatsReq\x1a#.booking_v1.booking.BookingStatsRep\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/bookings/statsB\rZ\v/booking_v1b\x06proto3"

var (
	file_booking_v1_booking_proto_rawDescOnce sync.Once
	file_booking_v1_booking_proto_rawDescData []byte
)

func file_booking_v1_booking_proto_rawDescGZIP() []byte {
	file_booking_v1_booking_proto_rawDescOnce.Do(func() {
		file_booking_v1_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_booking_proto_rawDesc), len(file_booking_v1_booking_proto_rawDesc)))
	})
	return file_booking_v1_booking_proto_rawDescData
}

var file_booking_v1_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_booking_v1_booking_proto_goTypes = []any{
	(*BookingMain)(nil),             // 0: booking_v1.booking.BookingMain
	(*BookingListReq)(nil),          // 1: booking_v1.booking.BookingListReq
	(*BookingListRep)(nil),          // 2: booking_v1.booking.BookingListRep
	(*BookingGetReq)(nil),           // 3: booking_v1.booking.BookingGetReq
	(*BookingCreateReq)(nil),        // 4: booking_v1.booking.BookingCreateReq
	(*BookingConfirmReq)(nil),       // 5: booking_v1.booking.BookingConfirmReq
	(*BookingCancelReq)(nil),        // 6: booking_v1.booking.BookingCancelReq
	(*BookingStatsReq)(nil),         // 7: booking_v1.booking.BookingStatsReq
	(*BookingStatsRep)(nil),         // 8: booking_v1.booking.BookingStatsRep
	(*DayStat)(nil),                 // 9: booking_v1.booking.DayStat
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
	(*common.ListParamsSt)(nil),     // 11: common.ListParamsSt
	(*common.PaginationInfoSt)(nil), // 12: common.PaginationInfoSt
}
var file_booking_v1_booking_proto_depIdxs = []int32{
	10, // 0: booking_v1.booking.BookingMain.start_at:type_name -> google.protobuf.Timestamp
	10, // 1: booking_v1.booking.BookingMain.end_at:type_name -> google.protobuf.Timestamp
	10, // 2: booking_v1.booking.BookingMain.created_at:type_name -> google.protobuf.Timestamp
	10, // 3: booking_v1.booking.BookingMain.updated_at:type_name -> google.protobuf.Timestamp
	10, // 4: booking_v1.booking.BookingMain.hold_expires_at:type_name -> google.protobuf.Timestamp
	10, // 5: booking_v1.booking.BookingMain.cancelled_at:type_name -> google.protobuf.Timestamp
	10, // 6: booking_v1.booking.BookingMain.confirmed_at:type_name -> google.protobuf.Timestamp
	10, // 7: booking_v1.booking.BookingMain.completed_at:type_name -> google.protobuf.Timestamp
	11, // 8: booking_v1.booking.BookingListReq.list_params:type_name -> common.ListParamsSt
	10, // 9: booking_v1.booking.BookingListReq.from:type_name -> google.protobuf.Timestamp
	10, // 10: booking_v1.booking.BookingListReq.to:type_name -> google.protobuf.Timestamp
	12, // 11: booking_v1.booking.BookingListRep.pagination_info:type_name -> common.PaginationInfoSt
	0,  // 12: booking_v1.booking.BookingListRep.results:type_name -> booking_v1.booking.BookingMain
	10, // 13: booking_v1.booking.BookingCreateReq.start_at:type_name -> google.protobuf.Timestamp
	10, // 14: booking_v1.booking.BookingCreateReq.end_at:type_name -> google.protobuf.Timestamp
	10, // 15: booking_v1.booking.BookingStatsReq.from:type_name -> google.protobuf.Timestamp
	10, // 16: booking_v1.booking.BookingStatsReq.to:type_name -> google.protobuf.Timestamp
	9,  // 17: booking_v1.booking.BookingStatsRep.revenue_by_day:type_name -> booking_v1.booking.DayStat
	9,  // 18: booking_v1.booking.BookingStatsRep.bookings_by_day:type_name -> booking_v1.booking.DayStat
	1,  // 19: booking_v1.booking.Booking.List:input_type -> booking_v1.booking.BookingListReq
	3,  // 20: booking_v1.booking.Booking.Get:input_type -> booking_v1.booking.BookingGetReq
	4,  // 21: booking_v1.booking.Booking.Create:input_type -> booking_v1.booking.BookingCreateReq
	5,  // 22: booking_v1.booking.Booking.Confirm:input_type -> booking_v1.booking.BookingConfirmReq
	6,  // 23: booking_v1.booking.Booking.Cancel:input_type -> booking_v1.booking.BookingCancelReq
	7,  // 24: booking_v1.booking.Booking.Stats:input_type -> booking_v1.booking.BookingStatsReq
	2,  // 25: booking_v1.booking.Booking.List:output_type -> booking_v1.booking.BookingListRep
	0,  // 26: booking_v1.booking.Booking.Get:output_type -> booking_v1.booking.BookingMain
	0,  // 27: booking_v1.booking.Booking.Create:output_type -> booking_v1.booking.BookingMain
	0,  // 28: booking_v1.booking.Booking.Confirm:output_type -> booking_v1.booking.BookingMain
	0,  // 29: booking_v1.booking.Booking.Cancel:output_type -> booking_v1.booking.BookingMain
	8,  // 30: booking_v1.booking.Booking.Stats:output_type -> booking_v1.booking.BookingStatsRep
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_booking_v1_booking_proto_init() }
func file_booking_v1_booking_proto_init() {
	if File_booking_v1_booking_proto != nil {
		return
	}
	file_booking_v1_booking_proto_msgTypes[0].OneofWrappers = []any{}
	file_booking_v1_booking_proto_msgTypes[1].OneofWrappers = []any{}
	file_booking_v1_booking_proto_msgTypes[4].OneofWrappers = []any{}
	file_booking_v1_booking_proto_msgTypes[5].OneofWrappers = []any{}
	file_booking_v1_booking_proto_msgTypes[6].OneofWrappers = []any{}
	file_booking_v1_booking_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_booking_proto_rawDesc), len(file_booking_v1_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_v1_booking_proto_goTypes,
		DependencyIndexes: file_booking_v1_booking_proto_depIdxs,
		MessageInfos:      file_booking_v1_booking_proto_msgTypes,
	}.Build()
	File_booking_v1_booking_proto = out.File
	file_booking_v1_booking_proto_goTypes = nil
	file_booking_v1_booking_proto_depIdxs = nil
}
