// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: booking_v1/booking.proto

package booking_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Booking_List_FullMethodName    = "/booking_v1.booking.Booking/List"
	Booking_Get_FullMethodName     = "/booking_v1.booking.Booking/Get"
	Booking_Create_FullMethodName  = "/booking_v1.booking.Booking/Create"
	Booking_Confirm_FullMethodName = "/booking_v1.booking.Booking/Confirm"
	Booking_Cancel_FullMethodName  = "/booking_v1.booking.Booking/Cancel"
)

// BookingClient is the client API for Booking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookingClient interface {
	List(ctx context.Context, in *BookingListReq, opts ...grpc.CallOption) (*BookingListRep, error)
	Get(ctx context.Context, in *BookingGetReq, opts ...grpc.CallOption) (*BookingMain, error)
	Create(ctx context.Context, in *BookingCreateReq, opts ...grpc.CallOption) (*BookingMain, error)
	Confirm(ctx context.Context, in *BookingConfirmReq, opts ...grpc.CallOption) (*BookingMain, error)
	Cancel(ctx context.Context, in *BookingCancelReq, opts ...grpc.CallOption) (*BookingMain, error)
}

type bookingClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingClient(cc grpc.ClientConnInterface) BookingClient {
	return &bookingClient{cc}
}

func (c *bookingClient) List(ctx context.Context, in *BookingListReq, opts ...grpc.CallOption) (*BookingListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingListRep)
	err := c.cc.Invoke(ctx, Booking_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) Get(ctx context.Context, in *BookingGetReq, opts ...grpc.CallOption) (*BookingMain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingMain)
	err := c.cc.Invoke(ctx, Booking_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) Create(ctx context.Context, in *BookingCreateReq, opts ...grpc.CallOption) (*BookingMain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingMain)
	err := c.cc.Invoke(ctx, Booking_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) Confirm(ctx context.Context, in *BookingConfirmReq, opts ...grpc.CallOption) (*BookingMain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingMain)
	err := c.cc.Invoke(ctx, Booking_Confirm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) Cancel(ctx context.Context, in *BookingCancelReq, opts ...grpc.CallOption) (*BookingMain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingMain)
	err := c.cc.Invoke(ctx, Booking_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingServer is the server API for Booking service.
// All implementations must embed UnimplementedBookingServer
// for forward compatibility.
type BookingServer interface {
	List(context.Context, *BookingListReq) (*BookingListRep, error)
	Get(context.Context, *BookingGetReq) (*BookingMain, error)
	Create(context.Context, *BookingCreateReq) (*BookingMain, error)
	Confirm(context.Context, *BookingConfirmReq) (*BookingMain, error)
	Cancel(context.Context, *BookingCancelReq) (*BookingMain, error)
	mustEmbedUnimplementedBookingServer()
}

// UnimplementedBookingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBookingServer struct{}

func (UnimplementedBookingServer) List(context.Context, *BookingListReq) (*BookingListRep, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedBookingServer) Get(context.Context, *BookingGetReq) (*BookingMain, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedBookingServer) Create(context.Context, *BookingCreateReq) (*BookingMain, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBookingServer) Confirm(context.Context, *BookingConfirmReq) (*BookingMain, error) {
	return nil, status.Error(codes.Unimplemented, "method Confirm not implemented")
}
func (UnimplementedBookingServer) Cancel(context.Context, *BookingCancelReq) (*BookingMain, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedBookingServer) mustEmbedUnimplementedBookingServer() {}
func (UnimplementedBookingServer) testEmbeddedByValue()                 {}

// UnsafeBookingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookingServer will
// result in compilation errors.
type UnsafeBookingServer interface {
	mustEmbedUnimplementedBookingServer()
}

func RegisterBookingServer(s grpc.ServiceRegistrar, srv BookingServer) {
	// If the following call panics, it indicates UnimplementedBookingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Booking_ServiceDesc, srv)
}

func _Booking_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Booking_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).List(ctx, req.(*BookingListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Booking_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).Get(ctx, req.(*BookingGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Booking_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).Create(ctx, req.(*BookingCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_Confirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingConfirmReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).Confirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Booking_Confirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).Confirm(ctx, req.(*BookingConfirmReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingCancelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Booking_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).Cancel(ctx, req.(*BookingCancelReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Booking_ServiceDesc is the grpc.ServiceDesc for Booking service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Booking_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "booking_v1.booking.Booking",
	HandlerType: (*BookingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Booking_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Booking_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Booking_Create_Handler,
		},
		{
			MethodName: "Confirm",
			Handler:    _Booking_Confirm_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Booking_Cancel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "booking_v1/booking.proto",
}
