// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: booking_v1/dict.proto

package booking_v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DictRep struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Legend          []*DictIdName          `protobuf:"bytes,1,rep,name=legend,proto3" json:"legend,omitempty"`
	AuditResources  []*DictIdName          `protobuf:"bytes,2,rep,name=audit_resources,json=auditResources,proto3" json:"audit_resources,omitempty"`
	AuditChangeType []*DictIdName          `protobuf:"bytes,3,rep,name=audit_change_type,json=auditChangeType,proto3" json:"audit_change_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DictRep) Reset() {
	*x = DictRep{}
	mi := &file_booking_v1_dict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictRep) ProtoMessage() {}

func (x *DictRep) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_dict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictRep.ProtoReflect.Descriptor instead.
func (*DictRep) Descriptor() ([]byte, []int) {
	return file_booking_v1_dict_proto_rawDescGZIP(), []int{0}
}

func (x *DictRep) GetLegend() []*DictIdName {
	if x != nil {
		return x.Legend
	}
	return nil
}

func (x *DictRep) GetAuditResources() []*DictIdName {
	if x != nil {
		return x.AuditResources
	}
	return nil
}

func (x *DictRep) GetAuditChangeType() []*DictIdName {
	if x != nil {
		return x.AuditChangeType
	}
	return nil
}

type DictIdName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictIdName) Reset() {
	*x = DictIdName{}
	mi := &file_booking_v1_dict_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictIdName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictIdName) ProtoMessage() {}

func (x *DictIdName) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_dict_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictIdName.ProtoReflect.Descriptor instead.
func (*DictIdName) Descriptor() ([]byte, []int) {
	return file_booking_v1_dict_proto_rawDescGZIP(), []int{1}
}

func (x *DictIdName) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DictIdName) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_booking_v1_dict_proto protoreflect.FileDescriptor

const file_booking_v1_dict_proto_rawDesc = "" +
	"\n" +
	"\x15booking_v1/dict.proto\x12\x0fbooking_v1.dict\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xcd\x01\n" +
	"\aDictRep\x123\n" +
	"\x06legend\x18\x01 \x03(\v2\x1b.booking_v1.dict.DictIdNameR\x06legend\x12D\n" +
	"\x0faudit_resources\x18\x02 \x03(\v2\x1b.booking_v1.dict.DictIdNameR\x0eauditResources\x12G\n" +
	"\x11audit_change_type\x18\x03 \x03(\v2\x1b.booking_v1.dict.DictIdNameR\x0fauditChangeType\">\n" +
	"\n" +
	"DictIdName\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name2\x85\x01\n" +
	"\x04Dict\x12F\n" +
	"\x03Get\x12\x16.google.protobuf.Empty\x1a\x18.booking_v1.dict.DictRep\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/dict\x1a5\x92A2\x120словарь ключевых значенийB\rZ\v/booking_v1b\x06proto3"

var (
	file_booking_v1_dict_proto_rawDescOnce sync.Once
	file_booking_v1_dict_proto_rawDescData []byte
)

func file_booking_v1_dict_proto_rawDescGZIP() []byte {
	file_booking_v1_dict_proto_rawDescOnce.Do(func() {
		file_booking_v1_dict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_dict_proto_rawDesc), len(file_booking_v1_dict_proto_rawDesc)))
	})
	return file_booking_v1_dict_proto_rawDescData
}

var file_booking_v1_dict_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_booking_v1_dict_proto_goTypes = []any{
	(*DictRep)(nil),       // 0: booking_v1.dict.DictRep
	(*DictIdName)(nil),    // 1: booking_v1.dict.DictIdName
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_booking_v1_dict_proto_depIdxs = []int32{
	1, // 0: booking_v1.dict.DictRep.legend:type_name -> booking_v1.dict.DictIdName
	1, // 1: booking_v1.dict.DictRep.audit_resources:type_name -> booking_v1.dict.DictIdName
	1, // 2: booking_v1.dict.DictRep.audit_change_type:type_name -> booking_v1.dict.DictIdName
	2, // 3: booking_v1.dict.Dict.Get:input_type -> google.protobuf.Empty
	0, // 4: booking_v1.dict.Dict.Get:output_type -> booking_v1.dict.DictRep
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_booking_v1_dict_proto_init() }
func file_booking_v1_dict_proto_init() {
	if File_booking_v1_dict_proto != nil {
		return
	}
	file_booking_v1_dict_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_dict_proto_rawDesc), len(file_booking_v1_dict_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_v1_dict_proto_goTypes,
		DependencyIndexes: file_booking_v1_dict_proto_depIdxs,
		MessageInfos:      file_booking_v1_dict_proto_msgTypes,
	}.Build()
	File_booking_v1_dict_proto = out.File
	file_booking_v1_dict_proto_goTypes = nil
	file_booking_v1_dict_proto_depIdxs = nil
}
