name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Download modules
        run: go mod download

#      - name: Go vet
#        run: go vet ./...

#      - name: Run tests
#        run: go test ./...

#      - name: GolangCI-Lint
#        uses: golangci/golangci-lint-action@v9
#        with:
#          version: latest
#          args: --timeout=5m

      - name: Check go mod tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
